name: "Test"

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Yarn Install
        run: yarn install

      # - name: Test Setup
      #   run: sudo apt-get install libgconf-2-4

      - name: Test
        run: yarn test